theme: jekyll-theme-minimal
description:  Research, Innovation and Experimentation of Internet Protocol Evolutions for Future and Emerging Applications
title: Operations and Control Networks, 6G Enablers, Innovations in Networks

github:
   project_tagline: Custom tagline
   owner_name: kiranmak@gmail.com
   
markdown: kramdown
